version: "3"
services:
  redis:
    container_name: kouryaku-redis
    image: "redis:latest"
    ports:
      - 6379:6379
    volumes:
      - ./kouryaku-env/redis/data:/data
  mysql:
    container_name: kouryaku-mysql
    build: ./kouryaku-env/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      TZ: "Asia/Tokyo"
    ports:
      - "3314:3306"
    volumes:
      - ./kouryaku-env/mysql/my.cnf:/etc/mysql/my.cnf
      - ./kouryaku-env/mysql/data:/var/lib/mysql
      - ./kouryaku-env/mysql/sql:/docker-entrypoint-initdb.d